services:
  gogogo-db:
    image: postgres:15
    container_name: gogogo-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env.prod
    networks:
      - gogogo-network

  redis:
    image: redis:7-alpine
    container_name: gogogo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gogogo-network

networks:
  gogogo-network:
    external: true

volumes:
  postgres_data:
  redis_data:
